databases:
  - name: blak_hat-db
    plan: free
    databaseName: blak_hat
    user: blak_hat

services:
  - type: web
    name: black-hat-md
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: SESSION_ID
        sync: false
      - key: MODE
        value: public
      - key: TIME_ZONE
        value: Africa/Nairobi
      - key: AUTO_LIKE_STATUS
        value: "true"
      - key: AUTO_READ_STATUS
        value: "true"
      - key: DATABASE_URL
        fromDatabase:
          name: blak_hat-db
          property: connectionString
